### ISSUE TITLE
Ignore generator functions

### ISSUE THREAD

**Issue by queengooborg** [JamieMason/eslint-plugin-prefer-arrow-functions#16]
There is no arrow syntax for generator functions, however an error is thrown when a generator function is found.  This rule should be ignored on generator functions.

**Comment by queengooborg** [comment]
Ah wait, my bad -- I thought this was the `prefer-arrow` plugin rather than a fork of it!  This fork is awesome though, especially with the auto-fixes, and we'll be using this fork in our own project from now on!

**Comment by JamieMason** [comment]
Great, I think/hope I have every case covered but if you do find I've missed anything around generators, let me know 👍🏻
