### ISSUE TITLE
More intelligent `returnStyle` option

### ISSUE THREAD

**Issue by u3u** [JamieMason/eslint-plugin-prefer-arrow-functions#21]
## Description

I hope that arrow functions can be forced to convert to `implicit` style when there is only one line.

```js
const arr = [0, 1, 2]

arr.filter((x) => {
  return x % 2 === 0
})

// ↓ ↓ ↓ ↓ ↓ ↓
arr.filter((x) => x % 2 === 0)
```

But if there are multiple lines, it can be forced to convert to the `explicit` style.

```js
export const delay = (timeout) =>
  new Promise((resolve) => {
    setTimeout(() => {
      resolve()
    }, timeout)
  })

// ↓ ↓ ↓ ↓ ↓ ↓
export const delay = (timeout) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve()
    }, timeout)
  })
}
```

This also makes it easier to extend `React` functional components.

```jsx
export const Button = () => (
  <button>
    <span></span>
  </button>
)

// ↓ ↓ ↓ ↓ ↓ ↓
export const Button = () => {
  return (
    <button>
      <span></span>
    </button>
  )
}
```

ref: https://github.com/eslint/eslint/issues/9062

## Suggested Solution

Add a new `smart` enumeration to the `returnStyle` option for intelligent judgment.

**Comment by u3u** [comment]
I implemented it myself.
https://github.com/u3u/eslint-plugin-arrow-return-style

/cc @tjbenton

**Comment by JamieMason** [comment]
Great work @u3u, thank you.
