### ISSUE TITLE
ESLint 9 support

### ISSUE THREAD

**Issue by loucyx** [JamieMason/eslint-plugin-prefer-arrow-functions#33]
## Description

- Use ESLint flat config.
- Upgrade ESLint to version 9.
- Run eslint with this plugin enabled.
- An error `context.getAncestors is not a function` is shown because that API was deprecated.

## Suggested Solution

Follow the following documentation from ESLint: https://eslint.org/docs/latest/use/migrate-to-9.0.0

**Comment by JamieMason** [comment]
Thanks @loucyx that would be great

**Comment by aeadedoyin** [comment]
Hi @JamieMason does this mean you are working it now?

**Comment by JamieMason** [comment]
I think @loucyx has everything they need there – I don't have any projects which have been upgraded to v9 so I haven't experienced that or have a project I'm using to test against, plus they have all the documentation on hand.

**Comment by loucyx** [comment]
I can try to create a PR here giving your plugin compatibility with ESLint 9, but other than that the consumers of your plugin can't use it in the latest version of ESLint because it uses deprecated APIs.

**Comment by JamieMason** [comment]
Thanks @loucyx, that's great. So that way anyone on ESLint 9 can use the next version of this plugin with your changes, and anyone still on older versions of ESLint can just stay on the current version of this plugin until they're ready.

**Comment by loucyx** [comment]
PR open [here](https://github.com/JamieMason/eslint-plugin-prefer-arrow-functions/pull/34) ☺️

**Comment by JamieMason** [comment]
Thanks a lot @loucyx 🎉 I will try to pick this up but it could be a week from now due to my availability.

**Comment by loucyx** [comment]
@JamieMason of course! Take all the time you need! 😄

**Comment by tiavina-mika** [comment]
Is there any news on this?

**Comment by JamieMason** [comment]
No news just yet, my spare time at the moment is focused on [syncpack](https://github.com/JamieMason/syncpack), once that settles I should have some more time.

**Comment by nabato** [comment]
So?

**Comment by nabato** [comment]
Any news?

**Comment by JamieMason** [comment]
Released in [3.4.0](https://github.com/JamieMason/eslint-plugin-prefer-arrow-functions/releases/tag/3.4.0).
